name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on any tag that starts with 'v'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history to get commit messages
        
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Get release template
        id: get_template
        run: |
          if [ -f ".github/RELEASE_TEMPLATE.md" ]; then
            template=$(cat .github/RELEASE_TEMPLATE.md)
            echo "TEMPLATE<<EOF" >> $GITHUB_OUTPUT
            echo "$template" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "TEMPLATE=# Release ${{ steps.get_version.outputs.VERSION }}" >> $GITHUB_OUTPUT
          fi
        shell: bash
        
      - name: Get commit messages
        id: get_commits
        run: |
          # Get all tags sorted by version
          all_tags=$(git tag -l | sort -V)
          
          # Get current tag from ref
          current_tag=${GITHUB_REF#refs/tags/}
          
          # Find the previous tag
          previous_tag=""
          found_current=false
          
          for tag in $all_tags; do
            if [ "$found_current" = true ]; then
              previous_tag=$tag
              break
            fi
            
            if [ "$tag" = "$current_tag" ]; then
              found_current=true
            else
              previous_tag=$tag
            fi
          done
          
          echo "Current tag: $current_tag"
          echo "Previous tag: $previous_tag"
          
          if [ -z "$previous_tag" ]; then
            # If no previous tag, get recent commits (limit to 20)
            echo "No previous tag found, getting recent commits"
            commit_list=$(git log -20 --pretty=format:"- %s" | grep -v "Merge pull request" | grep -v "Merge branch" || echo "- Initial release")
          else
            # Get commits between previous tag and current tag
            echo "Getting commits between $previous_tag and $current_tag"
            commit_list=$(git log --pretty=format:"- %s" $previous_tag..$current_tag | grep -v "Merge pull request" | grep -v "Merge branch" || echo "- No direct commits found")
          fi
          
          # Get pull request titles (with fallback)
          if [ -z "$previous_tag" ]; then
            pr_list=$(git log -20 --pretty=format:"%s" | grep "Merge pull request" | sed 's/Merge pull request #[0-9]* from [^/]*\///g' | sed 's/-/ /g' | sed 's/_/ /g' | sed 's/^/- /' || echo "")
          else
            pr_list=$(git log --pretty=format:"%s" $previous_tag..$current_tag | grep "Merge pull request" | sed 's/Merge pull request #[0-9]* from [^/]*\///g' | sed 's/-/ /g' | sed 's/_/ /g' | sed 's/^/- /' || echo "")
          fi
          
          # Ensure we have at least one item in the lists
          if [ -z "$commit_list" ]; then
            commit_list="- Updates and improvements"
          fi
          
          echo "COMMITS<<EOF" >> $GITHUB_OUTPUT
          echo "$commit_list" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "PULL_REQUESTS<<EOF" >> $GITHUB_OUTPUT
          echo "$pr_list" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "PREVIOUS_TAG=$previous_tag" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Create enhanced release notes
        id: release_notes
        run: |
          version="${{ steps.get_version.outputs.VERSION }}"
          commits="${{ steps.get_commits.outputs.COMMITS }}"
          pull_requests="${{ steps.get_commits.outputs.PULL_REQUESTS }}"
          current_tag="${GITHUB_REF#refs/tags/}"
          
          # Get the template content
          template_content="${{ steps.get_template.outputs.TEMPLATE }}"
          
          # Start with the template and replace version placeholders
          notes="$template_content"
          notes="${notes/VERSION/$version}"
          
          # Populate What's New section with PRs
          if [ ! -z "$pull_requests" ]; then
            # Replace the placeholder in What's New section
            notes="${notes/\<!-- List new features and improvements --\>\n- /$pull_requests}"
          else
            # If no PRs, use commits for What's New
            notes="${notes/\<!-- List new features and improvements --\>\n- /$commits}"
          fi
          
          # Extract bug fix related commits
          bug_fixes=$(echo "$commits" | grep -i "fix\|bug\|issue\|crash\|error" || echo "")
          
          # If we found bug fixes, populate the Bug Fixes section
          if [ ! -z "$bug_fixes" ]; then
            notes="${notes/\<!-- List fixed issues --\>\n- /$bug_fixes}"
          else
            # If no bug fixes found, leave a placeholder
            notes="${notes/\<!-- List fixed issues --\>\n- /- No specific bug fixes in this release\n}"
          fi
          
          # Get previous tag from the get_commits step output
          previous_tag="${{ steps.get_commits.outputs.PREVIOUS_TAG }}"
          
          # If previous_tag is empty, use a fallback
          if [ -z "$previous_tag" ]; then
            # Add a link to the full changelog on GitHub without comparison
            changelog_link="\n\n**Full Changelog**: https://github.com/memstechtips/Winhance/commits/$current_tag"
          else
            # Add a link to the full changelog on GitHub with comparison
            changelog_link="\n\n**Full Changelog**: https://github.com/memstechtips/Winhance/compare/$previous_tag...$current_tag"
          fi
          
          notes="${notes/## Known Issues/$changelog_link\n\n## Known Issues}"
          
          echo "NOTES<<EOF" >> $GITHUB_OUTPUT
          echo -e "$notes" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Winhance v${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.release_notes.outputs.NOTES }}
          draft: true # Create as draft so you can upload files manually
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          generate_release_notes: true # Enable GitHub's automatic release notes generation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
